language: python
dist: focal
sudo: true

python:
  - 3.9.1
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip3 install pipenv
  - pipenv sync -d

scripts:
  - pipenv run flake8 .
  - pipenv run pytest --cov=gestao_contratos

after_success:
  - pipenv run codecov