language: python
dist: focal
sudo: true

python:
  - 3.9.1

env:
  - SECRET_KEY='SOME_SCRET_KEY'
  - DEBUG=True
  - ALLOWED_HOSTS='.localhost, 127.0.0.1, .herokuapp.com'


install:
  - pip install -r requirements.txt

scripts:
  - pytest
