# Generated by Django 3.2 on 2021-04-23 21:58

from django.db import migrations, models
import django.db.models.deletion
import gestao_contratos.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, validators=[gestao_contratos.core.validators.name_validator],
                                          verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('cpf', models.CharField(max_length=14,
                                         unique=True, validators=[gestao_contratos.core.validators.cpf_validator],
                                         verbose_name='cpf')),
                ('rg', models.CharField(max_length=14, verbose_name='rg')),
            ],
            options={
                'verbose_name': 'atleta',
                'verbose_name_plural': 'atletas',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30, verbose_name='país')),
                ('state', models.CharField(max_length=30, verbose_name='estado')),
                ('city', models.CharField(max_length=30, verbose_name='cidade')),
                ('street', models.CharField(max_length=30, verbose_name='logradouro')),
                ('number', models.CharField(max_length=10, verbose_name='número')),
                ('complement', models.CharField(blank=True, max_length=10, verbose_name='complemento')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.athlete')),
            ],
            options={
                'verbose_name': 'endereço',
                'verbose_name_plural': 'endereços',
            },
        ),
    ]
